<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=5.0, minimum-scale=1.0, user-scalable=yes" />
    
        <meta http-equiv="content-language" content="en-US">
    
        <link rel="stylesheet" property="stylesheet" href="styles.css" type="text/css">
    
    
        <link rel="preconnect dns-prefetch" href="https://fonts.googleapis.com/" crossorigin>
        <link rel="preconnect dns-prefetch" href="https://ka-p.fontawesome.com/" crossorigin>
        <link rel="preconnect dns-prefetch" href="https://www.gstatic.com/">
        <link rel="preconnect dns-prefetch" href="https://kit.fontawesome.com/" crossorigin>
        <link rel="preconnect dns-prefetch" href="https://cdn.jsdelivr.net/">
        <link rel="preconnect dns-prefetch" href="https://cdnjs.cloudflare.com/">
        <link rel="preconnect dns-prefetch" href="https://fonts.gstatic.com/" crossorigin>
        <link rel="preconnect dns-prefetch" href="https://www.google.com/">
    
        <link rel="preload" as="image" href="assets/images/logos/c-logo--light (4).png">
    
        <link rel="preload" as="style" href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@400;600;700&amp;display=swap">
    
    
        <link rel="stylesheet" media="print" onload="this.onload=null;this.removeAttribute('media');" href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@400;600;700&amp;display=swap">

    
        <link href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@400;600;700&amp;display=swap" rel="stylesheet">
   
        <script>window.MSInputMethodContext && document.documentMode && document.write('<script src="assets/scripts/ie11CustomProperties.html"><\x2fscript>');</script>
    
    
        <link rel="icon" type="image/png" sizes="96x96" href="assets/icons/fav/favicon-96x96.png">
        <link rel="shortcut icon" type="image/png" sizes="96x96" href="assets/icons/fav/favicon-96x96.png">
        <link rel="icon" type="image/png" sizes="32x32" href="assets/icons/fav/favicon-32x32.png">
        <link rel="shortcut icon" type="image/png" sizes="32x32" href="assets/icons/fav/favicon-32x32.png">
        <link rel="icon" type="image/png" sizes="16x16" href="assets/icons/fav/favicon-16x16.png">
        <link rel="shortcut icon" type="image/png" sizes="16x16" href="assets/icons/fav/favicon-16x16.png">
        <link rel="apple-touch-icon" href="assets/icons/fav/apple-touch-icon.png">
        <link rel="shortcut icon" type="image/png" href="assets/icons/fav/favicon.ico">
        <link rel="icon" type="image/png" href="assets/icons/fav/favicon.ico">
    
        <script src="cdnjs.cloudflare.com/ajax/libs/modernizr/2.8.3/modernizr.min.js"></script>
    
        <script>
            document.querySelector('html').classList.remove('no-js');
        </script>
        <script src="javascript.js"></script>
    
        <script src='../www.google.com/recaptcha/apia192.js?render=6Ld1iWUlAAAAABb0Mf74D9V6MR7kZf41v3W0cjbd'></script>
    
        
        <title>OceanPulse Pump | Global distributors & Suppliers of Pumps</title>
        <meta property="og:type" content="website" />
        <link rel="canonical" href="index.html" />
        <meta name="description" content="OceanPulse is your trusted industrial pump supplier, offering a wide range of high-quality pumps and replacement parts. Contact us for reliable solutions." />

        <!-- Open Graph Tags -->
        <meta property="og:title" content="Industrial Pump Suppliers | OceanPulse" />
        <meta property="og:description" content="OceanPulse is your trusted industrial pump supplier, offering a wide range of high-quality pumps and replacement parts. Contact us for reliable solutions." />
        <meta property="og:image" content="https://www.OceanPulse.com/getmedia/714b61ef-e46c-47c6-b613-67916811aa6e/149209_Bowen-777-dump-trucks.jpg?width=1200&height=630&ext=.jpg" />
        <meta property="og:image:secure_url" content="https://www.OceanPulse.com/getmedia/714b61ef-e46c-47c6-b613-67916811aa6e/149209_Bowen-777-dump-trucks.jpg?width=1200&height=630&ext=.jpg" />
        <meta property="og:url" content="https://www.OceanPulse.com/services/industrial-pumps/" />
        <meta property="og:type" content="website" />
        
        <!-- Twitter Tags -->
        <meta property="twitter:title" content="Industrial Pump Suppliers | OceanPulse" />
        <meta property="twitter:description" content="OceanPulse is your trusted industrial pump supplier, offering a wide range of high-quality pumps and replacement parts. Contact us for reliable solutions." />
        <meta property="twitter:image" content="https://www.OceanPulse.com/getmedia/714b61ef-e46c-47c6-b613-67916811aa6e/149209_Bowen-777-dump-trucks.jpg?width=1200&height=630&ext=.jpg" />
        <meta property="twitter:card" content="summary_large_image" />
        <meta name="twitter:site" content="@OceanPulse" />
        
        <!-- Facebook App ID -->
        <meta property="fb:app_id" content="1558927977710718" />
        

    
        <link href="styles.css" rel="stylesheet" />
    
    </head>
<body>
    <!-- Header Section -->
    <header>
        <div class="logo">
            <img src="assets/icons/fav/logo.png" alt="Ocean Pulse Logo">
          </div>
        <nav class="c-main-nav" aria-label="main">
            <ul> <li class="has--drop">
                <a href="index.html">Home</a>
                <li class="has--drop">
                    <a href="About/About.html">About</a>
                    <button aria-controls="drop-menu-2104" aria-expanded="false"></button>
                    <ul id="drop-menu-2104" aria-labelledby="2104-label">
                        <li><a href="About/Vision Values Commitments.html">Vision, Values &amp; Commitments</a></li>
                        <li><a href="About/Leadership.html">Leadership</a></li>
                        <li><a href="About/Ethics.html">Ethics</a></li>
                        <li><a href="Locations/Locations.html">Locations</a></li>
                        <li><a href="About/Regions.html">Regions</a></li>
                    </ul>
                </li>
                <li class="has--drop">
                    <a href="Products/products.html">Products</a>
                    <button aria-controls="drop-menu-2256" aria-expanded="false"></button>
                    <ul id="drop-menu-2256" aria-labelledby="2256-label">
                        <li><a href="Slurry pumps.html">Slurry pumps</a></li>
                        <li><a href="Self priming Pumps.html">Self priming Pumps</a></li>
                        <li><a href="Submersible Pumps.html">Submersible Pumps</a></li>
                        <li><a href="End Suction Pumps.html">End Suction Pumps</a></li>
                        <li><a href="Split Case Pumps.html">Split Case Pumps</a></li>
                    </ul>
                </li>
                <li class="has--drop">
                    <a href="./Pump Replacement Parts/">Pump Replacement Parts</a>
                    <button aria-controls="drop-menu-2257" aria-expanded="false"></button>
                    <ul id="drop-menu-2257" aria-labelledby="2257-label">
                        <li><a href="./Pump Replacement Parts/Frame plate liners.html">Frame plate liners</a></li>
                        <li><a href="./Pump Replacement Parts/Impellers.html">Impellers</a></li>
                        <li><a href="./Pump Replacement Parts/Throatbushs.html">Throatbushs</a></li>
                        <li><a href="./Pump Replacement Parts/Volute liners.html">Volute liners</a></li>
                        <li><a href="./Pump Replacement Parts/Lantern Rings.html">Lantern Rings</a></li>
                        <li><a href="./Pump Replacement Parts/Expellers.html">Expellers</a></li>
                        <li><a href="./Pump Replacement Parts/Expeller rings.html">Expeller rings</a></li>
                        <li><a href="./Pump Replacement Parts/Gland Rings.html">Gland Rings</a></li>
                        <li><a href="./Pump Replacement Parts/Labyrinths.html">Labyrinths</a></li>
                        <li><a href="./Pump Replacement Parts/Labyrinth locknuts.html">Labyrinth locknuts</a></li>
                        <li><a href="./Pump Replacement Parts/Shaft Sleeve.html">Shaft Sleeve</a></li>
                        <li><a href="./Pump Replacement Parts/Vortex finders.html">Vortex finders</a></li>
                        <li><a href="./Pump Replacement Parts/Cone liners.html">Cone liners</a></li>
                        <li><a href="./Pump Replacement Parts/Packings.html">Packings</a></li>
                        <li><a href="./Pump Replacement Parts/Stuffing Box.html">Stuffing Box</a></li>
                        <li><a href="./Pump Replacement Parts/Bearing Housing.html">Bearing Housing</a></li>
                        <li><a href="./Pump Replacement Parts/Bearing Sleeve.html">Bearing Sleeve</a></li>
                        <li><a href="./Pump Replacement Parts/Mounting Plates.html">Mounting Plates</a></li>
                        <li><a href="./Pump Replacement Parts/End Cover.html">End Cover</a></li>
                        <li><a href="./Pump Replacement Parts/Low End Cover.html">Low End Cover</a></li>
                        <li><a href="./Pump Replacement Parts/Bearing Seal.html">Bearing Seal</a></li>
                        <li><a href="./Pump Replacement Parts/Shaft Sleeve Ejector.html">Shaft Sleeve Ejector</a></li>
                        <li><a href="./Pump Replacement Parts/Piston Ring.html">Piston Ring</a></li>
                        <li><a href="./Pump Replacement Parts/Strainer.html">Strainer</a></li>
                        <li><a href="./Pump Replacement Parts/Lower Strainer.html">Lower Strainer</a></li>
                        <li><a href="./Pump Replacement Parts/Discharge Pipe Gasket.html">Discharge Pipe Gasket</a></li>
                        <li><a href="./Pump Replacement Parts/Flinger.html">Flinger</a></li>
                        <li><a href="./Pump Replacement Parts/Spacer Set.html">Spacer Set</a></li>
                        <li><a href="./Pump Replacement Parts/Discharge Pipe.html">Discharge Pipe</a></li>
                        <li><a href="./Pump Replacement Parts/Suction Pipe.html">Suction Pipe</a></li>
                    </ul>
                </li>
                <li class="has--drop">
                    <a href="#">Careers</a>
                    <button aria-controls="drop-menu-2252" aria-expanded="false"></button>
                    <ul id="drop-menu-2252" aria-labelledby="2252-label">
                        <li><a href="#">Professionals</a></li>
                        <li><a href="#">Early Career</a></li>
                        <li><a href="#">Craft Professionals</a></li>
                        <li><a href="#">Returners Program</a></li>
                    </ul>
                </li>
                <li class="has--drop">
                    <a href="Locations/Locations.html">Locations & Distributors</a>
                    <button aria-controls="drop-menu-2252" aria-expanded="false"></button>
                    <ul id="drop-menu-2252" aria-labelledby="2252-label">
                        <li><a href="Locations/Asia.html">Asia</a></li>
                        <li><a href="Locations/America.html">Australia</a></li>
                        <li><a href="Locations/Africa and Middle East.html">Africa and Middle East</a></li>
                        <li><a href="Locations/America.html">America</a></li>
                        <li><a href="Locations/Europe.html">Europe</a></li>
                    </ul>
                </li>
            </ul>
        </nav>
        
    </header>

    <!-- Hero Section -->
   <section class="hero">
        <div class="hero-content">
            <h1>Global Leading Pump Supplier</h1>
            <p>At OceanPulse Pump Ltd., we specialize in designing, manufacturing, and supplying top-quality heavy-duty/severe-duty slurry pumps, spare parts, and comprehensive pumping solutions. Our product portfolio includes self-priming pumps, submersible pumps, end suction pumps, and split case pumps.
            </p>
            <a href="contact.html" class="btn">Request Qoute</a>
        </div>
        <div class="hero-image">
            
            </div>
            
        </div>
    </section>

    <!-- Product Categories -->
    <section class="products">
        <h2>Supply. Install. Maintain.</h2>
        <div class="product-grid">
            <div class="product-item">
                <img src="assets/images/2-2TC Vertical Slurry Pump/2-2C TurboFlo Slurry Pump.jpg" alt="2-2C TurboFlo Slurry Pump">
                <h3>2-2C TurboFlo Slurry Pump</h3>
                <a href="./Products/2-2C TurboFlo Slurry Pump.html" class="btn">See More</a>
            </div>
            <div class="product-item">
                <img src="assets/images/40PV-SP Under liquid slurry pump/T150VCR-SP.jpg">
                <h3>2-2C TurboFlo Slurry Pump</h3>
                <a href="./Products/2-2C TurboFlo Slurry Pump.html" class="btn">See More</a>
            </div>
            <div class="product-item">
                <img src="assets/images/2-inch Impeller Corrosion Resistant Rubber Pump/TSI Series Rubber Lined Slurry Pump.jpg " alt="TSI Series Rubber Lined Slurry Pump">
                <h3>TSI Series Rubber Lined Slurry..</h3>
                <a href="./Products/TSI Series Rubber Lined Slurry Pump.html" class="btn">See More</a>
            </div>
            <div class="product-item">
                <img src="assets/images/3-2 slurry pump/150'HD C-RSH Heavy Duty (8).jpg" alt="Heat Pumps">
                <h3>150'HD C-RSH Heavy Duty</h3>
                <a href="./Products/150'HD C-RSH Heavy Duty.html" class="btn">See More</a>
            </div>
        </div>
    </section>

    <!-- Contact Form -->
    <section class="contact">
        <h2>Need a Custom-Built System or a Maintenance Plan?</h2>
        <p>Please drop us a line and our sales team will be in touch.</p>
        <form class="contact-form">
            <input type="text" placeholder="Name" required>
            <input type="email" placeholder="Email" required>
            <textarea placeholder="Message" rows="5" required></textarea>
            <button type="submit" class="btn">Send</button>
        </form>
    </section>

      <!-- Footer -->
      <footer class="footer">
        <div class="footer-container">
          <div class="footer-about">
            <img src="./assets/icons/fav/logo.png" alt="OceanPulse logo" class="footer-logo">
            <p>
            
At OceanPulse Pump Ltd., we specialize in designing, manufacturing, and supplying top-quality heavy-duty/severe-duty slurry pumps, spare parts, and comprehensive pumping solutions. Our product portfolio includes self-priming pumps, submersible pumps, end suction pumps, and split case pumps.
            </p>
            <ul class="footer-contact">
                <li><span>âœ‰</span> info@OceanPulse.com</li>
                <li><span>âœ‰</span> sales@OceanPulse.com</li>
                <li><span>âœ‰</span> customercare@OceanPulse.comm</li>
                <li><span>ðŸ“ž</span> +86-576-86425284</li>
              </ul>
          </div>
          <div class="footer-links">
            <h4>NAVIGATION</h4>
            <ul>
              <li><a href="./About/About.html">About Us</a></li>
              <li><a href="./Products/products.html">Products</a></li>
              <li><a href="./Pump Replacement Parts/">Pump Replacement Parts</a></li>
              <li><a href="#">Careers</a></li>
              <li> <a href="Locations/Locations.html">Locations & Distributors</a></li>
              <li><a href="./contact.html">Contacts</a></li>
            </ul>
          </div>
          <div class="footer-links">
            <h4>PRODUCT</h4>
            <ul>
              <li><a href="Slurry pumps.html">Slurry pumps</a></li>
              <li><a href="Self priming Pumps.html">Self priming Pumps</a></li>
              <li><a href="Submersible Pumps.html">Submersible Pumps</a></li>
              <li><a href="End Suction Pumps.html">End Suction Pumps</a></li>
              <li><a href="Split Case Pumps.html">Split Case Pumps</a></li>
            </ul>
          </div>
        </div>
      </footer>

    <script src="script.js"></script>
</body>
</html>
<script>
document.addEventListener('DOMContentLoaded', () => {
    const header = document.querySelector('header');
    let lastScrollY = 0;

    const handleScroll = () => {
        const currentScrollY = window.scrollY;

        if (currentScrollY > lastScrollY) {
            // Scrolling down, hide the header
            header.classList.remove('visible-header');
            header.classList.add('hidden-header');
        } else {
            // Scrolling up, show the header
            header.classList.remove('hidden-header');
            header.classList.add('visible-header');
        }

        lastScrollY = currentScrollY;
    };

    window.addEventListener('scroll', handleScroll);
});

</script>
